const features=[{"n": "01", "t": "Cross-Vendor Agent Identity Registry", "d": "Unified agent identity records across custom runtimes and cloud providers."}, {"n": "02", "t": "Hierarchical Agent Delegation Graph", "d": "Human \u2192 manager \u2192 agent \u2192 sub-agent \u2192 tool authority lineage."}, {"n": "03", "t": "Dynamic Context-Aware Risk & Policy Engine", "d": "Runtime decisions using policy, action, spend and context."}, {"n": "04", "t": "Agent Spend & Resource Guardrails", "d": "Hard caps and circuit-breaker decisions before execution."}, {"n": "05", "t": "Management-by-Exception Escalation", "d": "Route high-risk deviations to a human workflow."}, {"n": "06", "t": "Degraded Execution & Hard Kill Switch", "d": "Restrict or terminate an agent immediately."}, {"n": "07", "t": "Shadow-Agent & Tool Discovery Scanner", "d": "Discovery surface for unregistered agents and tools."}, {"n": "08", "t": "Cryptographic Proof-of-Execution Graph", "d": "Hash-linked execution evidence with verification."}, {"n": "09", "t": "Cross-Vendor Non-Repudiation Vault", "d": "Immutable object-store adapters for evidence retention."}, {"n": "10", "t": "Agent Intent & Authority Verification", "d": "Check intended actions against delegated authority and policy."}, {"n": "11", "t": "Transaction Reversal & State Recovery", "d": "Record and coordinate recovery/compensating workflows."}, {"n": "12", "t": "Cross-Organization Agent Dispute Resolution", "d": "Evidence-backed dispute records between organizations."}];
document.querySelector("#cards").innerHTML=features.map(x=>`<article><small>${x.n}</small><h3>${x.t}</h3><p>${x.d}</p></article>`).join("");
async function loadHealth(){
  const r=await fetch("/health"); document.querySelector("#out").textContent=JSON.stringify(await r.json(),null,2);
  try {
    const i=await fetch("/integrations"); const d=await i.json();
    document.querySelector("#integrations").innerHTML=Object.values(d).map(x=>`<article><small>${x.provider.toUpperCase()}</small><h3>${x.configured?"CONNECTED":"NOT CONFIGURED"}</h3><p>${x.capability}<br>${x.detail}</p></article>`).join("");
  } catch(e) { document.querySelector("#integrations").innerHTML="<article>Authentication is required for integration status.</article>"; }
}
loadHealth();
